### PR TITLE
add: priority-fix: removing bug

### PR DESCRIPTION
**Pull request by Logan-Fouts**
I wanted to add some functionality for myself but thought why not see if you wanted to merge it for yourself

# New Feature
Added so users can set priorities for each todo. If they match h,m,l then they will print with associated colors.

# Fix
A noticed when I would remove an item but then put the index as a char it would core dump, so I added a quick check to make sure that wont happen.

### CODE REVIEW

**Comment by Logan-Fouts** [comment]
@l6174

**Comment by sekiryl** [comment]
Thanks for the contribution. This addition is awesome!

**Comment by sekiryl** [comment]
The cli and rofi are broken after this merge I will try to fix and push it with the respective changes soon.

**Comment by Logan-Fouts** [comment]
Oh my bad, I didnt test those. Worst case just roll back a commit

**Comment by sekiryl** [comment]
I have fixed those and pushed the changes. Now priorities work everywhere!

**Comment by Logan-Fouts** [comment]
Awesome, nice job :+1:

**Pull request merged**
